# Generated by Django 3.0.8 on 2020-07-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='name',
        ),
        migrations.AddField(
            model_name='username',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
