# Generated by Django 3.0.8 on 2020-07-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200726_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='user',
            new_name='name',
        ),
    ]
